platform :ios, '9.0'
use_frameworks!

target 'KMZN' do


 pod 'AFNetworking'
 pod 'SVProgressHUD'
 pod 'ObjectMapper', '~> 3.1.0'
 pod 'Starscream'
 pod 'Kingfisher' 
 pod 'DZNEmptyDataSet'
 pod 'JPush'
 
 pod 'mob_sharesdk'
 pod 'mob_sharesdk/ShareSDKPlatforms/WeChat'
 pod 'mob_sharesdk/ShareSDKPlatforms/Copy'
 pod 'mob_sharesdk/ShareSDKPlatforms/SMS'

end
